# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: create env file
        run: |
          touch .env
          echo BCRYPT_SALT_ROUNDS =${{ secrets.BCRYPT_SALT_ROUNDS }} >> .env
          echo JWT_SECRET =${{ secrets.JWT_SECRET }} >> .env
          echo MONGO_DB_URL_DEVELOPMENT =${{ secrets.MONGO_DB_URL_DEVELOPMENT }} >> .env
          echo MONGO_DB_URL_TEST =${{ secrets.MONGO_DB_URL_TEST }} >> .env
          echo MONGO_DB_URL_PRODUCTION =${{ secrets.MONGO_DB_URL_PRODUCTION }} >> .env
      - run: npm ci
      - run: npm run lint:js
      - run: npm run lint:format:check
      - run: npm run test
